### ISSUE TITLE
validation-logic.php does not use GET or POST?

### ISSUE THREAD

**Issue by bret-blackford** [susanBuck/dwa15-spring2019#20]
The validation.php code has a form that does not explicitly use GET or POST (that I can tell).  Not sure how Form class constructor gets form data without GET or POST.  Appears that a Form object is instantiated immediately (as part of validation-logic.php) but when file loads there is no data loaded in form ?

**Comment by susanBuck** [comment]
Forms will default to GET if no `method` is explicitly set. You can tell because when you [submit the form](http://php.dwa15.com/validation.php) you'll see all the data appended to the url. 

Regarding the form object being instantiated immediately:
```
$form = new DWA\Form($_GET);
```

When the page is first loaded, yes, $_GET will be empty since the form has not been submitted. However, the Form class is useful even in this case of an empty request, because we can do things like this:

```
$submitted = $form->isSubmitted();
```

For those browsing this thread, here are the relevant files we're discussing:
+ [validation.php](https://github.com/susanBuck/dwa15-php/blob/master/validation.php)
+ [validation-logic.php](https://github.com/susanBuck/dwa15-php/blob/master/validation-logic.php)
+ [demo](http://php.dwa15.com/validation.php)

**Comment by bret-blackford** [comment]
Thanks …
Fought thru and got things to work.
