### ISSUE TITLE
Week 7, Part 5 - is Laravel a Rube Goldberg machine? 

### ISSUE THREAD

**Issue by bret-blackford** [susanBuck/dwa15-spring2019#30]
This lecture has my head spinning.  It seems that Laravel and associated environment introduces quite a bit of complexity but I’m not yet seeing the return (a lot of squeeze for a little juice).  Perhaps when we get to Db access the use case for Laravel will become more clear.  After lecture Week 7, part 5 it seems that Laravel has taken basic php and  obfuscated wherever possible.

Hopefully after spending more time with Laravel things will make more sense.

**Comment by susanBuck** [comment]
I felt the same way when learning about frameworks. It was frustrating to have to relearn how to do all these things I already knew how to do, and it made development feel slow and over engineered. 

With time however, I came to appreciate all the utility it provided and building apps became so fluid.

A couple years ago I needed to throw together a simple app quickly and thought “this is so small I’ll just use pure php - a framework would be overkill”. I quickly realized how much utility the framework provided though, and I found myself missing all these tools/features and had to focus so much on building what those features provided (rather than the features of the app itself).

I also remember having similar feelings when learning about things like git and CSS pre-processors years ago. More utilities that added complexity to my existing workflows. But again, once they clicked, it’s hard to imagine development before them.

So my advice is to stick with it. There is a “hump” in the learning curve to get over, but it’s definitely worth it once you do.

**Comment by gjrett** [comment]
I managed to get everything working, but it took me sometime to realize where all the parts needed to be so they fell in line with the program sequencing.  I'd appreciate learning the path the processing takes through this framework.

Thanks.


Greg

**Comment by susanBuck** [comment]
> "I'd appreciate learning the path the processing takes through this framework."

Are you referring here to the request lifecycle we looked at in Week 6 (relevant [notes](https://github.com/susanBuck/dwa15-spring2019/blob/master/laravel/basic-flow.md#request-lifecycle), [video](https://www.youtube.com/embed/XdKru6h9zkM?rel=0&showinfo=0))? If so, I'm assuming you mean you're interested in taking a deeper dive into this topic? 

Or are you referring to something else?

**Comment by gjrett** [comment]
Yes I believe a deeper dive is what I need.  My application currently has a command, two views, two Classes and 2 Processing PHP pages.  Variables are passed between them using a session.  Getting this all set in the right places and correct path declarations is what took most of my time.  
I think I understand how they interact (path of the program from one to another of these coded pages), but a review of this interaction would be beneficial.
Thanks.
Greg
    On ‎Monday‎, ‎March‎ ‎25‎, ‎2019‎ ‎12‎:‎23‎:‎10‎ ‎PM‎ ‎CDT, Susan Buck <notifications@github.com> wrote:  
 
 

"I'd appreciate learning the path the processing takes through this framework."


Are you referring here to the request lifecycle we looked at in Week 6 (relevant notes, video)? If so, I'm assuming you mean you're interested in taking a deeper dive into this topic?

Or are you referring to something else?

**Comment by susanBuck** [comment]
Here's a 2-part blog post that does a deep dive into the Laravel lifecycle

+ [Part 1 Laravel Behind the Scenes: Lifecycle - Container](https://crnkovic.me/laravel-behind-the-scenes-lifecycle-container/)
+ [Part 2 Laravel Behind the Scenes: Lifecycle - Boot the framework](https://crnkovic.me/laravel-behind-the-scenes-lifecycle-boot-the-framework/)

And here's a useful graphic I found from [another blog post](http://blog.mallow-tech.com/2016/06/request-life-cycle-of-laravel/) that summarizes the process:
![image](https://user-images.githubusercontent.com/237711/55018545-761acf00-4fc9-11e9-897e-53baf347cd38.png)
