### ISSUE TITLE
Blade Templates

### ISSUE THREAD

**Issue by bret-blackford** [susanBuck/dwa15-spring2019#32]
Well, I've been working on adding the template to my project, starting with the 2 new files discussed in class: resources/views/layouts/***master.blade.php*** and resources/views/book/***show.blade.php***

I've added the files as discussed in the notes and the lecture but not sure how to call this from the URL.  I run the file(s) from the IDE and I see the page but the placeholders do not get fleshed out.

So, I guess the first question is, how do I call this from the URL?  This URL just brings back the prior webpage (http://www.bret-dwa15.vip/BMI-Laravel/public/) .  In the video lecture I see an resources/views/books/***index.blade.php*** file was created but this is not in the notes.  Is this a necessary file?

Files are uploaded to my GitHub repository here … https://github.com/bret-blackford/BMI-Laravel

**Comment by bret-blackford** [comment]
Wait … I think I've made some progress

**Comment by bret-blackford** [comment]
OK. Finally have the template working and loading correctly in prod from http://www.bret-dwa15.vip/BMI-Laravel/public/calc (or http://www.bret-dwa15.vip/BMI-Laravel/public/calc/Beatles as an example of passing in a parameter).  Things looking better. However, not able to get the .css file to load.  Are my absolute path directives correct as follows  -- 
```php
<link href='/css/bmi.css' type='text/css' rel='stylesheet'>
```

**Comment by susanBuck** [comment]
Hi Bret -

First thing - we need to sort out the URL you're using to access your project, as I suspect that might be the underlying cause of your CSS issue.

You're using `http://www.bret-dwa15.vip/BMI-Laravel/public/calc`.

But recall that we set things up so that each project should have a subdomain that points directly to the appropriate `public/` directory for that project, e.g. `foobooks.dwa15.me`, or `bmi.bret-dwa15.vip`.

Here's the relevant notes regarding that: 
+ Local: [New Laravel Application: Point local server to your new app](https://github.com/susanBuck/dwa15-spring2019/blob/master/laravel/new-laravel-app.md#point-local-server-to-your-new-app)
+ Production: [Deploy to DigitalOcean: Configure subdomain](https://github.com/susanBuck/dwa15-spring2019/blob/master/laravel/deploy-to-digital-ocean.md)

Without this set up correctly, your CSS path won't work. Here's why:

Site loads via `http://www.bret-dwa15.vip/BMI-Laravel/public/calc`
Attempts to load CSS via an absolute path of `/css/bmi.css`
This translates to `http://www.bret-dwa15.vip/css/bmi.css`

If things were set up correctly, the domain should map to `/BMI-Laravel/public` and so it would attempt to load `/BMI-Laravel/public/css/bmi.css` which would work. But because it's not, it fails.

As evidence of this, when I clone your project locally and set it up per the instructions, the CSS file does load. 

Please let me know if you have any questions straightening out the subdomain/document root. We can set up a time to troubleshoot if necessary.

**Comment by susanBuck** [comment]
Additional note - just to address your initial question for anyone else reading this thread with the same question:

>> "I've added the files as discussed in the notes and the lecture but not sure how to call this from the URL. I run the file(s) from the IDE and I see the page but the placeholders do not get fleshed out."

This is covered here: [Use your first view](https://github.com/susanBuck/dwa15-spring2019/blob/master/laravel/views-and-blade.md#use-your-first-view)

To summarize: The URL triggers the route, which triggers the action/method in the controller, which returns the view.

>> "In the video lecture I see an resources/views/books/index.blade.php file was created but this is not in the notes. Is this a necessary file?"

This was just a second example of a child view that I created (after setting up `show.blade.php`) to reinforce the process. It's possible to get `master.blade.php` and `show.blade.php` working without the `index.blade.php` example.

**Comment by bret-blackford** [comment]
Yes, using http://bmi-laravel.bret-dwa15.vip or http://bmi-laravel.bret-dwa15.vip/calc or http://bmi-laravel.bret-dwa15.vip/calc/SomeTextHere all now work and use .css as expected.

I usually wait to change /etc/apache2/sites-enabled/**000-default.conf** for the last step, after I've worked most of the bugs out of the code (as I prefer to use the default URL path).  After using the URL as directed in class the application can now find the correct absolute path to the .css file.

Thanks again.

**Comment by susanBuck** [comment]
Excellent, glad that sorted things out.
