### ISSUE TITLE
'dump' command not recognized in project directory

### ISSUE THREAD

**Issue by bibliodrone** [susanBuck/dwa15-spring2019#33]
Hi, I have found that the 'Dump' command does not work as expected when invoked in the context of a Laravel project folder. For example, in my local version of **C:\xampp\htdocs\foobooks**, I enter the command: `dump (config('mail'));` and receive the message,
``` 'dump' is not recognized as an internal or external command, operable program or batch file.```

I think I have Laravel installed properly; is there a straightfoward way to verify a Laravel installation, if that's the problem?

Or maybe I've just missed something obvious--it could be that as well. 

Thanks, 

Gerry

**Comment by bibliodrone** [comment]
I should have added that I am able to go to **config\mail.php** and view the settings in that file, so that is why I am unsure if there is something else missing.

**Comment by susanBuck** [comment]
Hi Gerry - 

Can you elaborate on where you're trying to invoke the command? In command line? In a file within your project? If so, what file (a view, a controller, etc.) ?

**Comment by bibliodrone** [comment]
I have been trying to invoke the command from the command line, from a project directory set up with Laravel, such as **c:/xampp/htdocs/p3** or **/foobooks**. Do I have to be in a particular sub-folder for the command to work? Maybe I just overlooked that detail.

**Comment by susanBuck** [comment]
Ok, I'm on track now with what you're trying to do.

`dump` is PHP code. It's a PHP function that our Laravel applications defines.

Because it's PHP code, we can't run it straight from command line - we have to be in some "PHP mode"

One way to do this via command line is to use Tinker - an interactive console for working with PHP code within your Laravel project.

If you revisit the [Week 6 assignment](https://canvas.harvard.edu/courses/54592/quizzes/125151), there was a question that showed how to use Tinker:

![image](https://user-images.githubusercontent.com/237711/55043705-c3b92b00-500d-11e9-9dcd-3f94712e9081.png)

Also, there's a brief mention of it in these notes: [Practice Work: Artisan Tinker](https://github.com/susanBuck/dwa15-spring2019/blob/master/laravel/practice-work.md#option-3-artisan-tinker)

With that info, see if you can get your example to work. If not, let me know and we can dig deeper.

**Comment by bibliodrone** [comment]
Susan, 

Thank you for bearing with me...that was the detail I overlooked. Commands like `config(dump('mail'));` work for me as expected, once **_artisan_** is running.

Gerry
