### ISSUE TITLE
php DateTime class

### ISSUE THREAD

**Issue by bret-blackford** [susanBuck/dwa15-spring2019#37]
in my P2 project I used the DateTime class in my BMIController.chex(() method and would like to use the same in P3.  Hoewever, I get the following error 
```
(1/1) ErrorClass 'App\Http\Controllers\DateTime' not found
--
in BMIController.php line 74

``` 

here is the offending code 
``` php
    $dob2 = new DateTime( $dob);
    $now = new DateTime();
    $difference = $now->diff($dob2);
    $age = $difference->y;
```

**Comment by susanBuck** [comment]
Once your in the controller's namespace, autoloading will look for classes within that namespace.

That's why the error reports that `App\Http\Controllers\DateTime` is not found - it's looking for `DateTime` within the `App\Http\Controllers\` namespace.

To fix this, add a `use` statement for the `DateTime` class at the top of the file with the other `use` statements:
```php
use DateTime;
```

This will effectively import the `DateTime` class from the global namespace, making it available for use.

Ref: [namespacing in controllers](https://github.com/susanBuck/dwa15-spring2019/blob/master/laravel/namespacing-in-controllers.md)

**Comment by bret-blackford** [comment]
Yes, that corrected isse
