### ISSUE TITLE
error connecting to foobooks Db

### ISSUE THREAD

**Issue by bret-blackford** [susanBuck/dwa15-spring2019#46]
I've created a foobooks project and associated Db to review the weeks lesson.  However, I get the following error trying to connect to the Db ...
```
array:2 [▼
  "Environment" => "local"
  "Database connection test" => "FAILED: SQLSTATE[HY000] [1045] Access denied for user 'homestead'@'localhost' (using password: YES) (SQL: SHOW DATABASES;)"
]
```

![image](https://user-images.githubusercontent.com/11459198/56462777-97839680-638e-11e9-8b1e-41780871f293.png)

My code is in github here ... https://github.com/bret-blackford/foobooks

**Comment by bret-blackford** [comment]
Argghh !!
OK. It looks like I needed no modify the `/.env` file.  I thought that was only necessary for Apple MAMP but my XAMPP only works with this file updated.  i though for XAMPP I needed to modify `/config/database.php`
Anyway, now get this ...
```
array:3 [▼
  "Environment" => "local"
  "Database connection test" => "PASSED"
  "Databases" => array:9 [▼
    0 => "bmi-p4"
    1 => "foobooks"
    2 => "information_schema"
    3 => "my_guitar_shop1"
    4 => "my_guitar_shop2"
    5 => "mysql"
    6 => "performance_schema"
    7 => "phpmyadmin"
    8 => "test"
  ]
]
```

![image](https://user-images.githubusercontent.com/11459198/56463751-b4749580-639f-11e9-8768-eb9f7de4d0d6.png)

**Comment by liataun** [comment]
The `/config/database.php` file gets pushed to the public repository, so we do __NOT__ want to have user and password listed in that file. The `.env` file is by default excluded from git, because we want to set environment specific info like passwords there. (The database config file pulls from `.env` by default.)

As far as I know, the production setup is identical for all of us. Whether we use XAMPP or MAMP locally, the Digital Ocean server is LAMP.
