### ISSUE TITLE
error creating seeder

### ISSUE THREAD

**Issue by bret-blackford** [susanBuck/dwa15-spring2019#48]
I get the following error when attempting to create my seeder. My "labs" table seeds fine but my "patient" table has errors.

Code in github here ... https://github.com/bret-blackford/Patient_Lab_Data 

![image](https://user-images.githubusercontent.com/11459198/56858698-2d499380-6944-11e9-80d9-fdd210089b59.png)

**Comment by bret-blackford** [comment]
I tried several different things an could not figure out the issue.  Instead, I just decided to recreate a new table and seed it.  That worked.  
Instead of using the origin " patient" table I created and seeded a new "patients" table.

**Comment by susanBuck** [comment]
Glad you sorted it out! 

As you noted, the solution was to rename the table from `patient` to `patients`. Here's why that worked:

You have a model `Patient`, which will - by default - look for a table called `patients`. This is because there's a correlation between the names of models and their corresponding tables (see Convention #1 [described here](https://github.com/susanBuck/dwa15-spring2019/blob/master/laravel/db-eloquent.md#eloquent-expectations)).

Alternatively, you could have overridden this convention to force your `Patient` model to work with a `patient` table, as is described in the screenshot from the docs below. But, given a project in its early stages, it's better just to remake the table following the correct conventions.


ref: <https://laravel.com/docs/5.8/eloquent#eloquent-model-conventions>:
![image](https://user-images.githubusercontent.com/237711/56915873-98e74a00-6a85-11e9-8b90-270d4495f885.png)
