### ISSUE TITLE
Course Grading Rubric

### ISSUE THREAD

**Issue by llandau** [susanBuck/dwa15-spring2019#5]
Hi,

I have a question about the mapping of the letter grades. In the course homepage, I see that there is a [Grading](https://dwa15.com/work-and-grading) section. I have a question about the interpretation of the Grading Diagram.

![Grading Diagram](https://s3.amazonaws.com/dwa15.com/letter-grade-scale@2x.png)

I find the meaning of the percentage column here potentially ambiguous and possibly misaligned with what I've experienced in other courses. What does the percentage value listed in each row represent specifically? Is it the lower bound required for the grade listed in the row, the upper bound, a middle value or just an example? I could possibly see the case for each of these interpretations.

Specifically, what is the range for an `A-`? Is an `A-` 92.0%-95.9%? That seems a little off to have an A- at 95% right? Isn't 93% usually the cutoff for an A?

**Comment by susanBuck** [comment]
Hi @llandau - This question falls under the category of **course logistics** and should be emailed to me directly (please see [Issues Forum : Posting Policies](https://dwa15.com/issues-forum#Posting%20policies)). 

I'm going to answer the question, then clear it off of the forum in a day or so - and let's aim to keep the Issues forum on topic with curriculum/troubleshooting related questions moving forward.

Yes, the percentage row is the lower bound required for the grade listed. An A- 92.0%-95.9%. If it's helpful, [here's a spreadsheet](https://docs.google.com/spreadsheets/d/1DORoSP21W2LaGGioL-0f0aUnyk9hlUct58y_MlY2mAs/edit#gid=0) where you can enter different percentages and see dynamically what letter grade it translates to.

There's no set/required standard in HES for point to letter grade scale. For each course I teach, I use a letter grade scale that is balanced with the difficulty of the assignments and the average performance of the students across semesters. I also consider factors such as grade inflation and aim to have the point/letter values coincide with the goals of each letter grade.

For example, given the majority of students in this course tend to perform well (in the A and A- range) it makes sense to bump up the goal of A to a >=96 to more accurately capture the work of "extraordinary distinction".

Even with this stretch in the scale, it's still quite attainable to earn an A. As evidence of this, here's a breakdown of letter grades from last semester:

![image](https://user-images.githubusercontent.com/237711/52227951-0a489f80-287f-11e9-840b-c1027a124220.png)

**Comment by llandau** [comment]
Thanks for the clarification on the grading. This is very helpful to know.

I was also thinking this might be more of a logistic question but wasn't sure if other students might  appreciate the clarification on this as well.

**Comment by susanBuck** [comment]
No problem @llandau! Happy to clarify. 

I agree that this was the kind of question other students might have been curious about. 

The problem is, questions of this nature aren't always as productive. In past semesters when I didn't have this policy, the forum got cluttered with logistical questions that were not productive because they were specific to one student, or were already clearly answered somewhere else. Also, I've seen course-logistic questions answered inaccurately by fellow classmates, which only caused confusion until I was able to clarify.

Because of this, I try to encourage students to feel comfortable to reach out to me directly for any clarifications/questions they have about course-logistics, and if I think it's a productive question for other students to hear, I will share it with the class via an announcement.

This was probably more info/background than you were interested in, but I just wanted to explain the reasoning behind the policy. Thanks for understanding, and I hope this doesn't discourage you from future, curriculum-related posts!
