### ISSUE TITLE
Project 4 - Style for name of multi word Model?

### ISSUE THREAD

**Issue by liataun** [susanBuck/dwa15-spring2019#52]
I know that models link to tables, which are `snake_case_separated`, that single word models are `Book.php`, but what about multi word models? (I assume a multi word table needs to match with a multi word model...)

Classes are stated as `StudlyCaps` in PSR-1, but I do not see in our [notes](https://github.com/susanBuck/dwa15-spring2019/blob/master//laravel/db-conventions.md), PSR-1/-2, nor the intro to Models in Laravel docs as to what is correct for models. _Does Laravel handle snake_case to StudlyCaps as well as the plural(table) to singular(model)?_

Edit, for reference:
[Laravel Models](https://laravel.com/docs/5.2/quickstart#eloquent-models)
[PSR-1 Class names](https://www.php-fig.org/psr/psr-1/#3-namespace-and-class-names)

**Comment by liataun** [comment]
And I guess a related question, _will PhpStorm correctly handle refactoring of a model for a Laravel app, if I need to change a model's name? Or would the smart table associations get mess up?_

**Comment by liataun** [comment]
I found a Laravel doc [mention of snake case](https://laravel.com/docs/5.8/eloquent#defining-models), but it is not clear whether there are underscores or not underscores in the model names, because they don't give a _standard_ example of snake-case, multi-word, model names. Only how to override, with multi-word table, if your single word model name doesn't match the table name.

**Comment by dianebainbridge** [comment]
I had a hard time with this.  My database name is fuel_logs which when I tried str_singular gave me fuel_log. What worked for me was creating a model called FuelLog, no underscore.  I read about this somewhere but I read so many posts trying to figure this out I forget where

**Comment by susanBuck** [comment]
>> "Does Laravel handle snake_case to StudlyCaps as well as the plural(table) to singular(model)?"

Yup!

As you noted, PSR-1 says the class names should be `StudlyCaps`

Then, in the docs you referenced, it says:

>> By convention, the "snake case", plural name of the class will be used as the table name unless another name is explicitly specified. 

So, using Diane's example, if we have a model named `FuelLog` (`StudlyCaps`) that will correspond to a table called `fuel_logs` (`snake_case` plural).

To confirm this, I had Artisan generate a model called `FuelLog` and I added the `--migration` flag so it would also generate the migration:

```php
php artisan make:model FuelLog --migration
```

In the migration that it created, it set the table name up as `fuel_logs`.

```php
Schema::create('fuel_logs', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->timestamps();
});
```

FYI Diane - the `str_plural` and `str_singular` commands will convert plural <=> singular, but it won't do the conversion for StudlyCaps <=> snake_case so it can't be used alone to figure out the model to table name correlation.

But, there is a helper method for [studly case](https://laravel.com/docs/5.8/helpers#method-studly-case) and [snake case](https://laravel.com/docs/5.8/helpers#method-snake-case) that can help!

Combining these together, we can do some table <=> model name conversions like so:

Get the table name given the model name `FuelLog`:
```
>>> Str::plural(Str::snake('FuelLog'))
=> "fuel_logs"
```

Get the model name given the table name `fuel_logs`:
```
>>> Str::singular(Str::snake('fuel_logs'))
=> "fuel_log"
```

*Aside: in the above example, you'll notice I invoke the string helpers like `Str::plural()` instead of `str_plural()`. Both will work, but the docs use the `Str::` style because [in a recent update the `str_` style was deprecated](https://laravel-news.com/laravel-5-8-deprecates-string-and-array-helpers).*

**Comment by dianebainbridge** [comment]
Thanks for clarifying - this is very helpful!

**Comment by susanBuck** [comment]
I've been working on upgrading an app from Laravel 5.7 -> 5.8 this afternoon, and found this relevant note in the [upgrade guide](https://laravel.com/docs/5.8/upgrade#upgrade-5.8.0):

![image](https://user-images.githubusercontent.com/237711/57152135-a1e75c80-6da0-11e9-8705-07f605e7c0a5.png)

Seemed relevant to this thread so I thought i'd share. :)

**Comment by dianebainbridge** [comment]
Thanks for sending this is good to know.

**Comment by liataun** [comment]
Thanks, I think this covers my question. It feels weird to rely on the framework to provide names, but if I can get used to it, I can see how it will be really convenient!

**Comment by susanBuck** [comment]
Keep in mind you don't *have* to rely on the framework's conventions. They can always be manually defined in the Model. 

![image](https://user-images.githubusercontent.com/237711/57197271-48636700-6f33-11e9-95d1-c713f00b96e6.png)

This can be useful if you want to follow some other convention. Or, you can even manually set them using the convention if you find it helpful as a reminder to see what table is being used.
