### ISSUE TITLE
Call to a member function delete() on null

### ISSUE THREAD

**Issue by kisa7081** [susanBuck/dwa15-spring2019#54]
While taking the week 11 quiz, I wasn't sure what the answer to question 8 was, so I modified existing code in my PracticeController to call delete on a non-existent book to see the output:
```
$book = Book::where('id', '=', '444')->first();
$book->delete();
```
What I saw was the error, "Call to a member function delete() on null."  So when I saw my answer was wrong, I plugged in the actual code from the quiz (using "id" since the "author" column doesn't exist anymore):

```
$book = Book::where('id', '=', '777')->get();
$book->delete();
```
This gives a different error, "Method Illuminate\Database\Eloquent\Collection::delete does not exist." 
 
Why is there a difference in the two errors?

**Comment by susanBuck** [comment]
In the first code snippet, your query fetch method is `first` which will try and find a single instance of Book.

When it doesn't find anything, $book is null, resulting in the error `Call to a member function delete() on null.`.

In the second code snippet, your query fetch method is `get` which always returns a Collection - even if it finds no results (in which case it's just an empty Collection). And, as the error indicates, there's no `delete` method for a Collection (`Method Illuminate\Database\Eloquent\Collection::delete`).

Take away:
+ If using `first()`, always make sure your results are not null before trying to do a delete - otherwise you may get a `Call to a member function delete() on null."` error.
+ If using `get()`, realize you're getting a Collection back (which could be empty) and you must iterate through that Collection if you wish to delete the individual model instances.

For some examples of the difference between `first` and `get`, see the top of this note set: [Collections](https://github.com/susanBuck/dwa15-spring2019/blob/master/laravel/db-collections.md).

Let me know if you still have any pending questions about this. : )

**Comment by kisa7081** [comment]
Thanks, that makes sense.  I guess I had "null" on the brain.
